steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-python-app', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-python-app']

  # Step 3: Deploy the Docker image to Google Compute Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['compute', 'ssh', 'azaazmm', '--zone', 'us-central1-a', '--command', 'sudo docker pull gcr.io/$PROJECT_ID/my-python-app && sudo docker run -d -p 80:80 gcr.io/$PROJECT_ID/my-python-app']

images:
  - 'gcr.io/$PROJECT_ID/my-python-app'
